// AUTO-GENERATED by scripts/gen-deduction.mjs — do not edit by hand.
// Deduction Grid levels: 12 words in a small grid, each theme a connected
// 3-cell region. In play the words are hidden and only the tiles listed in
// `given` show a clue number (how many orthogonal neighbours share its theme);
// the rest are blank. Every level is solvable by pure deduction from its shown
// clues alone — no guessing — and therefore has one solution. Fewer givens =
// harder (tier 1 Easy … 3 Hard). cells[] is row-major (cols per row).

export interface DeductionCell {
  word: string;
  /** Theme index 0-3 (the solution colour for this cell). */
  cat: number;
}

export interface DeductionLevel {
  id: string;
  pivot: string;
  rows: number;
  cols: number;
  /** 1 Easy, 2 Medium, 3 Hard — fewer shown clues as the tier rises. */
  tier: number;
  /** Cell indices (row-major) that display their clue number; others are blank. */
  given: number[];
  categories: string[];
  cells: DeductionCell[];
}

export const DEDUCTION_LEVELS: DeductionLevel[] = [
  {
    "id": "star",
    "pivot": "STAR",
    "rows": 3,
    "cols": 4,
    "tier": 1,
    "given": [
      0,
      1,
      2,
      3,
      4,
      5,
      9,
      11
    ],
    "categories": [
      "Words for a celebrity",
      "Seen in the night sky",
      "___ + FISH",
      "Symbols & shapes"
    ],
    "cells": [
      {
        "word": "ICON",
        "cat": 0
      },
      {
        "word": "LEGEND",
        "cat": 0
      },
      {
        "word": "MOON",
        "cat": 1
      },
      {
        "word": "COMET",
        "cat": 1
      },
      {
        "word": "IDOL",
        "cat": 0
      },
      {
        "word": "JELLY",
        "cat": 2
      },
      {
        "word": "PLANET",
        "cat": 1
      },
      {
        "word": "HEART",
        "cat": 3
      },
      {
        "word": "CAT",
        "cat": 2
      },
      {
        "word": "SWORD",
        "cat": 2
      },
      {
        "word": "ARROW",
        "cat": 3
      },
      {
        "word": "CROSS",
        "cat": 3
      }
    ]
  },
  {
    "id": "rock",
    "pivot": "ROCK",
    "rows": 3,
    "cols": 4,
    "tier": 1,
    "given": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      8,
      10,
      11
    ],
    "categories": [
      "Music genres",
      "To move back and forth",
      "Bits of stone",
      "Hand-game throws"
    ],
    "cells": [
      {
        "word": "JAZZ",
        "cat": 0
      },
      {
        "word": "BLUES",
        "cat": 0
      },
      {
        "word": "SWAY",
        "cat": 1
      },
      {
        "word": "SWING",
        "cat": 1
      },
      {
        "word": "FOLK",
        "cat": 0
      },
      {
        "word": "PEBBLE",
        "cat": 2
      },
      {
        "word": "PAPER",
        "cat": 3
      },
      {
        "word": "WOBBLE",
        "cat": 1
      },
      {
        "word": "BOULDER",
        "cat": 2
      },
      {
        "word": "STONE",
        "cat": 2
      },
      {
        "word": "SCISSORS",
        "cat": 3
      },
      {
        "word": "LIZARD",
        "cat": 3
      }
    ]
  },
  {
    "id": "spring",
    "pivot": "SPRING",
    "rows": 3,
    "cols": 4,
    "tier": 1,
    "given": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      11
    ],
    "categories": [
      "Seasons",
      "To leap suddenly",
      "Sources of water",
      "Mechanical parts"
    ],
    "cells": [
      {
        "word": "SUMMER",
        "cat": 0
      },
      {
        "word": "WINTER",
        "cat": 0
      },
      {
        "word": "LEAP",
        "cat": 1
      },
      {
        "word": "POUNCE",
        "cat": 1
      },
      {
        "word": "WELL",
        "cat": 2
      },
      {
        "word": "AUTUMN",
        "cat": 0
      },
      {
        "word": "BOUND",
        "cat": 1
      },
      {
        "word": "GEAR",
        "cat": 3
      },
      {
        "word": "GEYSER",
        "cat": 2
      },
      {
        "word": "FOUNTAIN",
        "cat": 2
      },
      {
        "word": "COIL",
        "cat": 3
      },
      {
        "word": "LEVER",
        "cat": 3
      }
    ]
  },
  {
    "id": "light",
    "pivot": "LIGHT",
    "rows": 3,
    "cols": 4,
    "tier": 1,
    "given": [
      0,
      1,
      2,
      3,
      4,
      5,
      8,
      10
    ],
    "categories": [
      "Gives off light",
      "Not heavy",
      "___ + HOUSE",
      "To set ablaze"
    ],
    "cells": [
      {
        "word": "LAMP",
        "cat": 0
      },
      {
        "word": "TORCH",
        "cat": 0
      },
      {
        "word": "AIRY",
        "cat": 1
      },
      {
        "word": "SLIGHT",
        "cat": 1
      },
      {
        "word": "GREEN",
        "cat": 2
      },
      {
        "word": "CANDLE",
        "cat": 0
      },
      {
        "word": "IGNITE",
        "cat": 3
      },
      {
        "word": "FLUFFY",
        "cat": 1
      },
      {
        "word": "WARE",
        "cat": 2
      },
      {
        "word": "POWER",
        "cat": 2
      },
      {
        "word": "KINDLE",
        "cat": 3
      },
      {
        "word": "SPARK",
        "cat": 3
      }
    ]
  },
  {
    "id": "fire",
    "pivot": "FIRE",
    "rows": 4,
    "cols": 3,
    "tier": 1,
    "given": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      11
    ],
    "categories": [
      "Dismiss from a job",
      "Discharge a weapon",
      "Burning hot things",
      "Burning enthusiasm"
    ],
    "cells": [
      {
        "word": "SACK",
        "cat": 0
      },
      {
        "word": "CAN",
        "cat": 0
      },
      {
        "word": "SHOOT",
        "cat": 1
      },
      {
        "word": "AXE",
        "cat": 0
      },
      {
        "word": "BLAST",
        "cat": 1
      },
      {
        "word": "LAUNCH",
        "cat": 1
      },
      {
        "word": "FLAME",
        "cat": 2
      },
      {
        "word": "EMBER",
        "cat": 2
      },
      {
        "word": "PASSION",
        "cat": 3
      },
      {
        "word": "BLAZE",
        "cat": 2
      },
      {
        "word": "ZEAL",
        "cat": 3
      },
      {
        "word": "DRIVE",
        "cat": 3
      }
    ]
  },
  {
    "id": "pitch",
    "pivot": "PITCH",
    "rows": 4,
    "cols": 3,
    "tier": 1,
    "given": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      8,
      9,
      11
    ],
    "categories": [
      "Throw in baseball",
      "A sales spiel",
      "Musical highness",
      "Sports playing area"
    ],
    "cells": [
      {
        "word": "THROW",
        "cat": 0
      },
      {
        "word": "HURL",
        "cat": 0
      },
      {
        "word": "SPIEL",
        "cat": 1
      },
      {
        "word": "TOSS",
        "cat": 0
      },
      {
        "word": "PROPOSAL",
        "cat": 1
      },
      {
        "word": "PLUG",
        "cat": 1
      },
      {
        "word": "TONE",
        "cat": 2
      },
      {
        "word": "FIELD",
        "cat": 3
      },
      {
        "word": "COURT",
        "cat": 3
      },
      {
        "word": "KEY",
        "cat": 2
      },
      {
        "word": "NOTE",
        "cat": 2
      },
      {
        "word": "GROUND",
        "cat": 3
      }
    ]
  },
  {
    "id": "trunk",
    "pivot": "TRUNK",
    "rows": 4,
    "cols": 3,
    "tier": 1,
    "given": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      9,
      11
    ],
    "categories": [
      "Parts of a tree",
      "Car body parts",
      "On an elephant",
      "Storage boxes"
    ],
    "cells": [
      {
        "word": "BARK",
        "cat": 0
      },
      {
        "word": "HOOD",
        "cat": 1
      },
      {
        "word": "FENDER",
        "cat": 1
      },
      {
        "word": "ROOT",
        "cat": 0
      },
      {
        "word": "BRANCH",
        "cat": 0
      },
      {
        "word": "BUMPER",
        "cat": 1
      },
      {
        "word": "TUSK",
        "cat": 2
      },
      {
        "word": "TAIL",
        "cat": 2
      },
      {
        "word": "CHEST",
        "cat": 3
      },
      {
        "word": "EARS",
        "cat": 2
      },
      {
        "word": "CRATE",
        "cat": 3
      },
      {
        "word": "LOCKER",
        "cat": 3
      }
    ]
  },
  {
    "id": "bark",
    "pivot": "BARK",
    "rows": 4,
    "cols": 3,
    "tier": 2,
    "given": [
      0,
      1,
      2,
      3,
      8,
      9
    ],
    "categories": [
      "Dog sounds",
      "Found on a tree",
      "To shout harshly",
      "Kinds of boat"
    ],
    "cells": [
      {
        "word": "WOOF",
        "cat": 0
      },
      {
        "word": "SAP",
        "cat": 1
      },
      {
        "word": "RING",
        "cat": 1
      },
      {
        "word": "GROWL",
        "cat": 0
      },
      {
        "word": "YAP",
        "cat": 0
      },
      {
        "word": "KNOT",
        "cat": 1
      },
      {
        "word": "SHOUT",
        "cat": 2
      },
      {
        "word": "YACHT",
        "cat": 3
      },
      {
        "word": "CANOE",
        "cat": 3
      },
      {
        "word": "SNAP",
        "cat": 2
      },
      {
        "word": "SNARL",
        "cat": 2
      },
      {
        "word": "FERRY",
        "cat": 3
      }
    ]
  },
  {
    "id": "mint",
    "pivot": "MINT",
    "rows": 3,
    "cols": 4,
    "tier": 2,
    "given": [
      0,
      1,
      2,
      3,
      9,
      11
    ],
    "categories": [
      "Cooking herbs",
      "To make money",
      "Sweet treats",
      "Brand-new"
    ],
    "cells": [
      {
        "word": "BASIL",
        "cat": 0
      },
      {
        "word": "THYME",
        "cat": 0
      },
      {
        "word": "COIN",
        "cat": 1
      },
      {
        "word": "STAMP",
        "cat": 1
      },
      {
        "word": "SAGE",
        "cat": 0
      },
      {
        "word": "TOFFEE",
        "cat": 2
      },
      {
        "word": "PRINT",
        "cat": 1
      },
      {
        "word": "PRISTINE",
        "cat": 3
      },
      {
        "word": "FUDGE",
        "cat": 2
      },
      {
        "word": "CARAMEL",
        "cat": 2
      },
      {
        "word": "FRESH",
        "cat": 3
      },
      {
        "word": "NEW",
        "cat": 3
      }
    ]
  },
  {
    "id": "bank",
    "pivot": "BANK",
    "rows": 3,
    "cols": 4,
    "tier": 2,
    "given": [
      0,
      1,
      2,
      3,
      6,
      8,
      9,
      11
    ],
    "categories": [
      "Found in a bank",
      "Edge of a river",
      "To rely on",
      "To tilt while turning"
    ],
    "cells": [
      {
        "word": "VAULT",
        "cat": 0
      },
      {
        "word": "ATM",
        "cat": 0
      },
      {
        "word": "SHORE",
        "cat": 1
      },
      {
        "word": "LEVEE",
        "cat": 1
      },
      {
        "word": "TELLER",
        "cat": 0
      },
      {
        "word": "COUNT",
        "cat": 2
      },
      {
        "word": "TILT",
        "cat": 3
      },
      {
        "word": "EDGE",
        "cat": 1
      },
      {
        "word": "DEPEND",
        "cat": 2
      },
      {
        "word": "RELY",
        "cat": 2
      },
      {
        "word": "ROLL",
        "cat": 3
      },
      {
        "word": "LEAN",
        "cat": 3
      }
    ]
  },
  {
    "id": "check",
    "pivot": "CHECK",
    "rows": 3,
    "cols": 4,
    "tier": 2,
    "given": [
      0,
      1,
      2,
      3,
      4,
      5,
      8,
      11
    ],
    "categories": [
      "Chess terms",
      "To verify",
      "Restaurant payment",
      "Fabric patterns"
    ],
    "cells": [
      {
        "word": "MATE",
        "cat": 0
      },
      {
        "word": "CASTLE",
        "cat": 0
      },
      {
        "word": "VERIFY",
        "cat": 1
      },
      {
        "word": "INSPECT",
        "cat": 1
      },
      {
        "word": "BILL",
        "cat": 2
      },
      {
        "word": "ROOK",
        "cat": 0
      },
      {
        "word": "CONFIRM",
        "cat": 1
      },
      {
        "word": "PLAID",
        "cat": 3
      },
      {
        "word": "TAB",
        "cat": 2
      },
      {
        "word": "TOTAL",
        "cat": 2
      },
      {
        "word": "STRIPE",
        "cat": 3
      },
      {
        "word": "FLORAL",
        "cat": 3
      }
    ]
  },
  {
    "id": "bug",
    "pivot": "BUG",
    "rows": 3,
    "cols": 4,
    "tier": 2,
    "given": [
      0,
      1,
      2,
      3,
      8,
      10
    ],
    "categories": [
      "Creepy-crawlies",
      "To pester",
      "Software faults",
      "Spy gear"
    ],
    "cells": [
      {
        "word": "BEETLE",
        "cat": 0
      },
      {
        "word": "ANT",
        "cat": 0
      },
      {
        "word": "PESTER",
        "cat": 1
      },
      {
        "word": "ANNOY",
        "cat": 1
      },
      {
        "word": "GLITCH",
        "cat": 2
      },
      {
        "word": "FLEA",
        "cat": 0
      },
      {
        "word": "WIRE",
        "cat": 3
      },
      {
        "word": "NAG",
        "cat": 1
      },
      {
        "word": "ERROR",
        "cat": 2
      },
      {
        "word": "CRASH",
        "cat": 2
      },
      {
        "word": "TAP",
        "cat": 3
      },
      {
        "word": "MIC",
        "cat": 3
      }
    ]
  },
  {
    "id": "table",
    "pivot": "TABLE",
    "rows": 4,
    "cols": 3,
    "tier": 2,
    "given": [
      0,
      1,
      2,
      5,
      6,
      11
    ],
    "categories": [
      "Household furniture",
      "Ways to show data",
      "To postpone",
      "Billiards gear"
    ],
    "cells": [
      {
        "word": "CHAIR",
        "cat": 0
      },
      {
        "word": "DESK",
        "cat": 0
      },
      {
        "word": "CHART",
        "cat": 1
      },
      {
        "word": "STOOL",
        "cat": 0
      },
      {
        "word": "GRAPH",
        "cat": 1
      },
      {
        "word": "GRID",
        "cat": 1
      },
      {
        "word": "SHELVE",
        "cat": 2
      },
      {
        "word": "DEFER",
        "cat": 2
      },
      {
        "word": "CUE",
        "cat": 3
      },
      {
        "word": "DELAY",
        "cat": 2
      },
      {
        "word": "RACK",
        "cat": 3
      },
      {
        "word": "CHALK",
        "cat": 3
      }
    ]
  },
  {
    "id": "drop",
    "pivot": "DROP",
    "rows": 4,
    "cols": 3,
    "tier": 2,
    "given": [
      0,
      1,
      2,
      3,
      5,
      7,
      9,
      11
    ],
    "categories": [
      "Bit of liquid",
      "To fall sharply",
      "To abandon",
      "Hard candy"
    ],
    "cells": [
      {
        "word": "DROPLET",
        "cat": 0
      },
      {
        "word": "BEAD",
        "cat": 0
      },
      {
        "word": "PLUNGE",
        "cat": 1
      },
      {
        "word": "DRIP",
        "cat": 0
      },
      {
        "word": "SINK",
        "cat": 1
      },
      {
        "word": "DIVE",
        "cat": 1
      },
      {
        "word": "QUIT",
        "cat": 2
      },
      {
        "word": "TOFFEE",
        "cat": 3
      },
      {
        "word": "LOLLIPOP",
        "cat": 3
      },
      {
        "word": "DITCH",
        "cat": 2
      },
      {
        "word": "SCRAP",
        "cat": 2
      },
      {
        "word": "GUMDROP",
        "cat": 3
      }
    ]
  },
  {
    "id": "seal",
    "pivot": "SEAL",
    "rows": 4,
    "cols": 3,
    "tier": 3,
    "given": [
      0,
      2,
      4,
      6,
      9,
      11
    ],
    "categories": [
      "Marine animals",
      "To close up",
      "Official marks",
      "Elite soldiers"
    ],
    "cells": [
      {
        "word": "WALRUS",
        "cat": 0
      },
      {
        "word": "SHUT",
        "cat": 1
      },
      {
        "word": "CLOSE",
        "cat": 1
      },
      {
        "word": "NARWHAL",
        "cat": 0
      },
      {
        "word": "ORCA",
        "cat": 0
      },
      {
        "word": "FASTEN",
        "cat": 1
      },
      {
        "word": "STAMP",
        "cat": 2
      },
      {
        "word": "CREST",
        "cat": 2
      },
      {
        "word": "RANGER",
        "cat": 3
      },
      {
        "word": "EMBLEM",
        "cat": 2
      },
      {
        "word": "MARINE",
        "cat": 3
      },
      {
        "word": "COMMANDO",
        "cat": 3
      }
    ]
  },
  {
    "id": "bat",
    "pivot": "BAT",
    "rows": 4,
    "cols": 3,
    "tier": 3,
    "given": [
      2,
      3,
      8,
      9
    ],
    "categories": [
      "Creatures of the night",
      "Swung at a ball",
      "To flutter",
      "Cricket terms"
    ],
    "cells": [
      {
        "word": "OWL",
        "cat": 0
      },
      {
        "word": "RACKET",
        "cat": 1
      },
      {
        "word": "CLUB",
        "cat": 1
      },
      {
        "word": "MOTH",
        "cat": 0
      },
      {
        "word": "RACCOON",
        "cat": 0
      },
      {
        "word": "PADDLE",
        "cat": 1
      },
      {
        "word": "FLUTTER",
        "cat": 2
      },
      {
        "word": "WICKET",
        "cat": 3
      },
      {
        "word": "BOWLER",
        "cat": 3
      },
      {
        "word": "BLINK",
        "cat": 2
      },
      {
        "word": "WINK",
        "cat": 2
      },
      {
        "word": "CREASE",
        "cat": 3
      }
    ]
  },
  {
    "id": "deck",
    "pivot": "DECK",
    "rows": 3,
    "cols": 4,
    "tier": 3,
    "given": [
      0,
      2,
      9,
      11
    ],
    "categories": [
      "Parts of a ship",
      "In a card game",
      "To punch out",
      "Outdoor spaces"
    ],
    "cells": [
      {
        "word": "HULL",
        "cat": 0
      },
      {
        "word": "MAST",
        "cat": 0
      },
      {
        "word": "SUIT",
        "cat": 1
      },
      {
        "word": "ACE",
        "cat": 1
      },
      {
        "word": "BOW",
        "cat": 0
      },
      {
        "word": "SLUG",
        "cat": 2
      },
      {
        "word": "JOKER",
        "cat": 1
      },
      {
        "word": "PATIO",
        "cat": 3
      },
      {
        "word": "FLOOR",
        "cat": 2
      },
      {
        "word": "CLOCK",
        "cat": 2
      },
      {
        "word": "PORCH",
        "cat": 3
      },
      {
        "word": "VERANDA",
        "cat": 3
      }
    ]
  },
  {
    "id": "note",
    "pivot": "NOTE",
    "rows": 3,
    "cols": 4,
    "tier": 3,
    "given": [
      0,
      3,
      8,
      9,
      10,
      11
    ],
    "categories": [
      "Music symbols",
      "Quick messages",
      "Paper money",
      "To observe"
    ],
    "cells": [
      {
        "word": "REST",
        "cat": 0
      },
      {
        "word": "CLEF",
        "cat": 0
      },
      {
        "word": "MEMO",
        "cat": 1
      },
      {
        "word": "LETTER",
        "cat": 1
      },
      {
        "word": "SHARP",
        "cat": 0
      },
      {
        "word": "BILL",
        "cat": 2
      },
      {
        "word": "NOTICE",
        "cat": 3
      },
      {
        "word": "REMINDER",
        "cat": 1
      },
      {
        "word": "CASH",
        "cat": 2
      },
      {
        "word": "DOLLAR",
        "cat": 2
      },
      {
        "word": "OBSERVE",
        "cat": 3
      },
      {
        "word": "REMARK",
        "cat": 3
      }
    ]
  },
  {
    "id": "park",
    "pivot": "PARK",
    "rows": 3,
    "cols": 4,
    "tier": 3,
    "given": [
      0,
      1,
      3,
      6,
      8,
      11
    ],
    "categories": [
      "Green spaces",
      "To stop a car",
      "Amusement ___",
      "Baseball venues"
    ],
    "cells": [
      {
        "word": "GARDEN",
        "cat": 0
      },
      {
        "word": "MEADOW",
        "cat": 0
      },
      {
        "word": "STOP",
        "cat": 1
      },
      {
        "word": "HALT",
        "cat": 1
      },
      {
        "word": "FAIR",
        "cat": 2
      },
      {
        "word": "COMMON",
        "cat": 0
      },
      {
        "word": "IDLE",
        "cat": 1
      },
      {
        "word": "FIELD",
        "cat": 3
      },
      {
        "word": "CARNIVAL",
        "cat": 2
      },
      {
        "word": "ARCADE",
        "cat": 2
      },
      {
        "word": "STADIUM",
        "cat": 3
      },
      {
        "word": "DIAMOND",
        "cat": 3
      }
    ]
  },
  {
    "id": "wave",
    "pivot": "WAVE",
    "rows": 3,
    "cols": 4,
    "tier": 3,
    "given": [
      1,
      3,
      8,
      10
    ],
    "categories": [
      "At the seaside",
      "Gestures",
      "A ___ of heat",
      "Hair textures"
    ],
    "cells": [
      {
        "word": "TIDE",
        "cat": 0
      },
      {
        "word": "SURF",
        "cat": 0
      },
      {
        "word": "SALUTE",
        "cat": 1
      },
      {
        "word": "NOD",
        "cat": 1
      },
      {
        "word": "SURGE",
        "cat": 2
      },
      {
        "word": "SWELL",
        "cat": 0
      },
      {
        "word": "CURL",
        "cat": 3
      },
      {
        "word": "BECKON",
        "cat": 1
      },
      {
        "word": "SPELL",
        "cat": 2
      },
      {
        "word": "BLAST",
        "cat": 2
      },
      {
        "word": "FRIZZ",
        "cat": 3
      },
      {
        "word": "KINK",
        "cat": 3
      }
    ]
  }
];
