// AUTO-GENERATED by scripts/gen-deduction.mjs — do not edit by hand.
// Deduction Grid levels: 12 words in a 3×4 grid, each theme a connected
// 3-cell region. In play the words are hidden and each tile shows only its clue
// number (how many orthogonal neighbours share its theme); the clue grid has a
// unique solution. cells[] is row-major (4 per row).

export interface DeductionCell {
  word: string;
  /** Theme index 0-3 (the solution colour for this cell). */
  cat: number;
}

export interface DeductionLevel {
  id: string;
  pivot: string;
  rows: number;
  cols: number;
  categories: string[];
  cells: DeductionCell[];
}

export const DEDUCTION_LEVELS: DeductionLevel[] = [
  {
    "id": "star",
    "pivot": "STAR",
    "categories": [
      "Words for a celebrity",
      "Seen in the night sky",
      "___ + FISH",
      "Symbols & shapes"
    ],
    "cells": [
      {
        "word": "ICON",
        "cat": 0
      },
      {
        "word": "LEGEND",
        "cat": 0
      },
      {
        "word": "MOON",
        "cat": 1
      },
      {
        "word": "COMET",
        "cat": 1
      },
      {
        "word": "IDOL",
        "cat": 0
      },
      {
        "word": "JELLY",
        "cat": 2
      },
      {
        "word": "PLANET",
        "cat": 1
      },
      {
        "word": "HEART",
        "cat": 3
      },
      {
        "word": "CAT",
        "cat": 2
      },
      {
        "word": "SWORD",
        "cat": 2
      },
      {
        "word": "ARROW",
        "cat": 3
      },
      {
        "word": "CROSS",
        "cat": 3
      }
    ],
    "rows": 3,
    "cols": 4
  },
  {
    "id": "bug",
    "pivot": "BUG",
    "categories": [
      "Creepy-crawlies",
      "To pester",
      "Software faults",
      "Spy gear"
    ],
    "cells": [
      {
        "word": "BEETLE",
        "cat": 0
      },
      {
        "word": "ANT",
        "cat": 0
      },
      {
        "word": "PESTER",
        "cat": 1
      },
      {
        "word": "ANNOY",
        "cat": 1
      },
      {
        "word": "FLEA",
        "cat": 0
      },
      {
        "word": "GLITCH",
        "cat": 2
      },
      {
        "word": "WIRE",
        "cat": 3
      },
      {
        "word": "NAG",
        "cat": 1
      },
      {
        "word": "ERROR",
        "cat": 2
      },
      {
        "word": "CRASH",
        "cat": 2
      },
      {
        "word": "TAP",
        "cat": 3
      },
      {
        "word": "MIC",
        "cat": 3
      }
    ],
    "rows": 3,
    "cols": 4
  },
  {
    "id": "seal",
    "pivot": "SEAL",
    "categories": [
      "Marine animals",
      "To close up",
      "Official marks",
      "Elite soldiers"
    ],
    "cells": [
      {
        "word": "WALRUS",
        "cat": 0
      },
      {
        "word": "NARWHAL",
        "cat": 0
      },
      {
        "word": "SHUT",
        "cat": 1
      },
      {
        "word": "CLOSE",
        "cat": 1
      },
      {
        "word": "STAMP",
        "cat": 2
      },
      {
        "word": "ORCA",
        "cat": 0
      },
      {
        "word": "FASTEN",
        "cat": 1
      },
      {
        "word": "RANGER",
        "cat": 3
      },
      {
        "word": "CREST",
        "cat": 2
      },
      {
        "word": "EMBLEM",
        "cat": 2
      },
      {
        "word": "MARINE",
        "cat": 3
      },
      {
        "word": "COMMANDO",
        "cat": 3
      }
    ],
    "rows": 3,
    "cols": 4
  }
];
