// AUTO-GENERATED by scripts/gen-deduction.mjs — do not edit by hand.
// Deduction Grid levels: an abstract grid of 12 cells split into 4 hidden
// groups of 3. Groups can be ANY shapes (they do not have to touch). Some
// tiles carry a plain-text clue about their neighbours ("None of my
// neighbours are in my group", "The tile below me is in my group", …). Every
// level is solvable by pure reasoning from its shown clues alone — verified to
// have exactly one solution. Fewer clues = harder (tier 1 Easy … 3 Hard).
// solution[] is the group id (0-3) per cell, row-major (cols per row).

export type DeductionClue =
  | { cell: number; kind: "deg"; n: number }
  | { cell: number; kind: "dir"; dir: "up" | "down" | "left" | "right"; same: boolean };

export interface DeductionLevel {
  id: string;
  rows: number;
  cols: number;
  /** 1 Easy, 2 Medium, 3 Hard — fewer shown clues as the tier rises. */
  tier: number;
  clues: DeductionClue[];
  solution: number[];
}

export const DEDUCTION_LEVELS: DeductionLevel[] = [
  {
    "id": "logic-1",
    "rows": 3,
    "cols": 4,
    "tier": 1,
    "clues": [
      {
        "cell": 3,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 5,
        "kind": "dir",
        "dir": "right",
        "same": false
      },
      {
        "cell": 9,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 0,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 1,
        "kind": "dir",
        "dir": "left",
        "same": false
      },
      {
        "cell": 2,
        "kind": "dir",
        "dir": "right",
        "same": true
      },
      {
        "cell": 4,
        "kind": "deg",
        "n": 0
      }
    ],
    "solution": [
      0,
      1,
      2,
      2,
      1,
      0,
      3,
      2,
      0,
      1,
      3,
      3
    ]
  },
  {
    "id": "logic-2",
    "rows": 4,
    "cols": 3,
    "tier": 1,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 2,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 6,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 8,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 1,
        "kind": "dir",
        "dir": "down",
        "same": false
      },
      {
        "cell": 3,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 4,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 5,
        "kind": "dir",
        "dir": "down",
        "same": false
      }
    ],
    "solution": [
      0,
      1,
      1,
      0,
      2,
      1,
      2,
      3,
      3,
      0,
      2,
      3
    ]
  },
  {
    "id": "logic-3",
    "rows": 3,
    "cols": 4,
    "tier": 1,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 1,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 3,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 4,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 5,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 2,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 6,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 7,
        "kind": "dir",
        "dir": "down",
        "same": false
      },
      {
        "cell": 8,
        "kind": "deg",
        "n": 1
      }
    ],
    "solution": [
      0,
      1,
      2,
      2,
      0,
      3,
      3,
      2,
      0,
      3,
      1,
      1
    ]
  },
  {
    "id": "logic-4",
    "rows": 4,
    "cols": 3,
    "tier": 1,
    "clues": [
      {
        "cell": 2,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 4,
        "kind": "dir",
        "dir": "left",
        "same": true
      },
      {
        "cell": 7,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 8,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 9,
        "kind": "dir",
        "dir": "up",
        "same": true
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 11,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 0,
        "kind": "dir",
        "dir": "right",
        "same": false
      },
      {
        "cell": 1,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 3,
        "kind": "dir",
        "dir": "down",
        "same": false
      },
      {
        "cell": 5,
        "kind": "deg",
        "n": 1
      }
    ],
    "solution": [
      0,
      1,
      1,
      2,
      2,
      1,
      3,
      0,
      0,
      3,
      2,
      3
    ]
  },
  {
    "id": "logic-5",
    "rows": 3,
    "cols": 4,
    "tier": 1,
    "clues": [
      {
        "cell": 2,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 3,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 4,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 5,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 7,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 9,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 0,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 1,
        "kind": "dir",
        "dir": "right",
        "same": true
      },
      {
        "cell": 6,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 8,
        "kind": "dir",
        "dir": "right",
        "same": false
      }
    ],
    "solution": [
      0,
      1,
      1,
      2,
      0,
      3,
      1,
      3,
      0,
      2,
      2,
      3
    ]
  },
  {
    "id": "logic-6",
    "rows": 4,
    "cols": 3,
    "tier": 1,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 1,
        "kind": "dir",
        "dir": "down",
        "same": true
      },
      {
        "cell": 6,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 8,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 9,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 11,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 2,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 3,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 4,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 5,
        "kind": "deg",
        "n": 1
      }
    ],
    "solution": [
      0,
      1,
      1,
      2,
      1,
      3,
      2,
      3,
      3,
      0,
      0,
      2
    ]
  },
  {
    "id": "logic-7",
    "rows": 3,
    "cols": 4,
    "tier": 1,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 1,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 8,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 11,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 2,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 3,
        "kind": "dir",
        "dir": "left",
        "same": false
      },
      {
        "cell": 4,
        "kind": "dir",
        "dir": "up",
        "same": false
      },
      {
        "cell": 5,
        "kind": "dir",
        "dir": "right",
        "same": false
      }
    ],
    "solution": [
      0,
      1,
      1,
      0,
      2,
      1,
      0,
      3,
      2,
      2,
      3,
      3
    ]
  },
  {
    "id": "logic-8",
    "rows": 4,
    "cols": 3,
    "tier": 2,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 2,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 4,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 5,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 7,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 10,
        "kind": "dir",
        "dir": "right",
        "same": false
      },
      {
        "cell": 11,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 1,
        "kind": "dir",
        "dir": "left",
        "same": true
      },
      {
        "cell": 3,
        "kind": "deg",
        "n": 1
      }
    ],
    "solution": [
      0,
      0,
      1,
      0,
      2,
      1,
      3,
      2,
      3,
      2,
      1,
      3
    ]
  },
  {
    "id": "logic-9",
    "rows": 3,
    "cols": 4,
    "tier": 2,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 2,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 3,
        "kind": "dir",
        "dir": "down",
        "same": false
      },
      {
        "cell": 5,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 7,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 11,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 1,
        "kind": "dir",
        "dir": "down",
        "same": false
      },
      {
        "cell": 4,
        "kind": "dir",
        "dir": "right",
        "same": false
      }
    ],
    "solution": [
      0,
      0,
      1,
      1,
      0,
      2,
      2,
      3,
      3,
      2,
      1,
      3
    ]
  },
  {
    "id": "logic-10",
    "rows": 4,
    "cols": 3,
    "tier": 2,
    "clues": [
      {
        "cell": 1,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 4,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 5,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 8,
        "kind": "dir",
        "dir": "down",
        "same": false
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 11,
        "kind": "dir",
        "dir": "left",
        "same": true
      },
      {
        "cell": 0,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 2,
        "kind": "dir",
        "dir": "down",
        "same": false
      }
    ],
    "solution": [
      0,
      0,
      0,
      1,
      2,
      1,
      2,
      3,
      1,
      2,
      3,
      3
    ]
  },
  {
    "id": "logic-11",
    "rows": 3,
    "cols": 4,
    "tier": 2,
    "clues": [
      {
        "cell": 4,
        "kind": "dir",
        "dir": "right",
        "same": false
      },
      {
        "cell": 5,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 7,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 8,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 9,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 10,
        "kind": "dir",
        "dir": "right",
        "same": true
      },
      {
        "cell": 11,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 0,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 1,
        "kind": "deg",
        "n": 1
      }
    ],
    "solution": [
      0,
      1,
      2,
      3,
      0,
      1,
      1,
      3,
      0,
      3,
      2,
      2
    ]
  },
  {
    "id": "logic-12",
    "rows": 4,
    "cols": 3,
    "tier": 2,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 2,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 4,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 5,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 1,
        "kind": "dir",
        "dir": "left",
        "same": true
      },
      {
        "cell": 3,
        "kind": "dir",
        "dir": "down",
        "same": false
      }
    ],
    "solution": [
      0,
      0,
      1,
      0,
      2,
      1,
      1,
      2,
      2,
      3,
      3,
      3
    ]
  },
  {
    "id": "logic-13",
    "rows": 3,
    "cols": 4,
    "tier": 2,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 2,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 3,
        "kind": "dir",
        "dir": "down",
        "same": false
      },
      {
        "cell": 6,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 7,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 1,
        "kind": "dir",
        "dir": "left",
        "same": true
      },
      {
        "cell": 4,
        "kind": "dir",
        "dir": "right",
        "same": false
      }
    ],
    "solution": [
      0,
      0,
      1,
      1,
      0,
      2,
      3,
      2,
      3,
      3,
      1,
      2
    ]
  },
  {
    "id": "logic-14",
    "rows": 4,
    "cols": 3,
    "tier": 2,
    "clues": [
      {
        "cell": 1,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 7,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 11,
        "kind": "dir",
        "dir": "up",
        "same": true
      },
      {
        "cell": 0,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 2,
        "kind": "dir",
        "dir": "down",
        "same": false
      }
    ],
    "solution": [
      0,
      0,
      0,
      1,
      2,
      1,
      2,
      2,
      3,
      3,
      1,
      3
    ]
  },
  {
    "id": "logic-15",
    "rows": 3,
    "cols": 4,
    "tier": 3,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 1,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 2,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 8,
        "kind": "dir",
        "dir": "up",
        "same": true
      },
      {
        "cell": 9,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 2
      }
    ],
    "solution": [
      0,
      1,
      2,
      2,
      0,
      2,
      3,
      1,
      0,
      1,
      3,
      3
    ]
  },
  {
    "id": "logic-16",
    "rows": 4,
    "cols": 3,
    "tier": 3,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 1,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 2,
        "kind": "dir",
        "dir": "down",
        "same": false
      },
      {
        "cell": 3,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 7,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 8,
        "kind": "dir",
        "dir": "up",
        "same": true
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 2
      }
    ],
    "solution": [
      0,
      1,
      1,
      2,
      2,
      0,
      2,
      1,
      0,
      3,
      3,
      3
    ]
  },
  {
    "id": "logic-17",
    "rows": 3,
    "cols": 4,
    "tier": 3,
    "clues": [
      {
        "cell": 2,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 5,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 8,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 2
      }
    ],
    "solution": [
      0,
      1,
      0,
      1,
      2,
      1,
      3,
      0,
      2,
      2,
      3,
      3
    ]
  },
  {
    "id": "logic-18",
    "rows": 4,
    "cols": 3,
    "tier": 3,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 1,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 6,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 8,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 9,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 11,
        "kind": "deg",
        "n": 0
      }
    ],
    "solution": [
      0,
      1,
      1,
      2,
      1,
      3,
      2,
      2,
      3,
      0,
      3,
      0
    ]
  },
  {
    "id": "logic-19",
    "rows": 3,
    "cols": 4,
    "tier": 3,
    "clues": [
      {
        "cell": 0,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 2,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 3,
        "kind": "dir",
        "dir": "left",
        "same": true
      },
      {
        "cell": 4,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 11,
        "kind": "deg",
        "n": 2
      }
    ],
    "solution": [
      0,
      1,
      0,
      0,
      2,
      2,
      1,
      3,
      2,
      1,
      3,
      3
    ]
  },
  {
    "id": "logic-20",
    "rows": 4,
    "cols": 3,
    "tier": 3,
    "clues": [
      {
        "cell": 3,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 8,
        "kind": "deg",
        "n": 2
      },
      {
        "cell": 9,
        "kind": "deg",
        "n": 1
      },
      {
        "cell": 10,
        "kind": "deg",
        "n": 0
      },
      {
        "cell": 11,
        "kind": "deg",
        "n": 0
      }
    ],
    "solution": [
      0,
      1,
      1,
      0,
      0,
      2,
      3,
      2,
      2,
      3,
      1,
      3
    ]
  }
];
